"""Count RDF triples or quads in compressed or uncompressed files."""

from __future__ import annotations

import argparse
import fnmatch
import gzip
import multiprocessing
import os
import zipfile
from collections.abc import Iterable, Mapping, Sequence
from functools import partial
from multiprocessing import Pool
from pathlib import Path
from typing import TextIO

import orjson
from rich_argparse import RichHelpFormatter

from oc_meta.lib.console import create_progress
from oc_meta.lib.file_manager import collect_files

QUAD_FORMATS = {"nquads"}
LINE_BASED_FORMATS = {"nquads", "nt"}
JSONLD_SPECIAL_KEYS = {"@id", "@context", "@graph", "@list", "@set", "@language", "@value"}


def _count_jsonld_value(value: object) -> int:
    """Count triples generated by a JSON-LD property value."""
    if isinstance(value, list):
        return sum(_count_jsonld_value(item) for item in value)
    if isinstance(value, dict):
        if "@list" in value:
            return _count_jsonld_value(value["@list"])
        if "@set" in value:
            return _count_jsonld_value(value["@set"])
        if "@value" in value:
            return 1
        if "@id" in value and len(value) == 1:
            return 1
        return 1 + _count_jsonld_object(value)
    return 1


def _count_jsonld_object(obj: Mapping[str, object]) -> int:
    """Count triples for a single JSON-LD object."""
    count = 0
    for key, value in obj.items():
        if key in JSONLD_SPECIAL_KEYS:
            continue
        if key == "@type":
            if isinstance(value, list):
                count += len(value)
            else:
                count += 1
        else:
            count += _count_jsonld_value(value)
    return count


def _count_jsonld_triples(data: Mapping[str, object] | Sequence[object]) -> int:
    """Count triples in a JSON-LD document without RDFLib parsing."""
    if isinstance(data, Sequence) and not isinstance(data, (str, bytes)):
        total = 0
        for obj in data:
            if isinstance(obj, dict):
                if "@graph" in obj:
                    graph = obj["@graph"]
                    if isinstance(graph, list):
                        total += sum(
                            _count_jsonld_object(item)
                            for item in graph
                            if isinstance(item, dict)
                        )
                else:
                    total += _count_jsonld_object(obj)
        return total
    if isinstance(data, Mapping):
        if "@graph" in data:
            graph = data["@graph"]
            if isinstance(graph, list):
                return sum(
                    _count_jsonld_object(obj) for obj in graph if isinstance(obj, dict)
                )
        return _count_jsonld_object(data)
    return 0


def parse_args() -> argparse.Namespace:  # pragma: no cover
    parser = argparse.ArgumentParser(
        description="Count RDF triples or quads in compressed or uncompressed files.",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "directory",
        type=Path,
        help="Directory containing the RDF files.",
    )
    parser.add_argument(
        "--pattern",
        default="*.nq.gz",
        help="Glob pattern for locating files (default: '*.nq.gz').",
    )
    parser.add_argument(
        "--format",
        default="nquads",
        choices=["nquads", "nt", "json-ld"],
        help="RDF format of the input files (default: nquads).",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Search recursively under the provided directory.",
    )
    parser.add_argument(
        "--prov-only",
        action="store_true",
        help="Count only files in 'prov' subdirectories.",
    )
    parser.add_argument(
        "--data-only",
        action="store_true",
        help="Count only files not in 'prov' subdirectories.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=None,
        help="Number of parallel workers (default: CPU count).",
    )
    parser.add_argument(
        "--show-per-file",
        action="store_true",
        help="Print the count for each processed file.",
    )
    parser.add_argument(
        "--keep-going",
        action="store_true",
        help="Continue processing even if errors occur.",
    )
    return parser.parse_args()


def discover_files(
    directory: Path,
    pattern: str,
    recursive: bool,
    prov_only: bool,
    data_only: bool,
) -> list[Path]:
    path = directory.expanduser().resolve()
    if not path.is_dir():
        raise ValueError(f"'{path}' does not exist or is not a directory.")

    root_str = str(path)

    if recursive:

        def path_filter(p: str) -> bool:
            is_prov = "/prov" in p or p.endswith("/prov")
            if prov_only and not is_prov:
                return False
            if data_only and is_prov:
                return False
            return True

        str_files = collect_files(root_str, pattern, path_filter)
        return sorted(Path(f) for f in str_files)

    is_prov = path.name == "prov"
    if (prov_only and not is_prov) or (data_only and is_prov):
        return []

    files: list[Path] = []
    for entry in os.scandir(root_str):
        if entry.is_file() and fnmatch.fnmatch(entry.name, pattern):
            files.append(Path(entry.path))
    return sorted(files)


def _count_lines_binary(file_obj: Iterable[bytes]) -> int:
    count = 0
    for line_num, line in enumerate(file_obj, 1):
        stripped = line.strip()
        if not stripped or stripped.startswith(b"#"):
            continue
        if not stripped.endswith(b"."):
            raise ValueError(f"line {line_num}: statement does not end with '.'")
        count += 1
    return count


def _count_lines_text(file_obj: TextIO) -> int:
    count = 0
    for line_num, line in enumerate(file_obj, 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not stripped.endswith("."):
            raise ValueError(f"line {line_num}: statement does not end with '.'")
        count += 1
    return count


def count_in_file(
    file_path: Path, rdf_format: str
) -> tuple[str, int, str | None]:
    try:
        suffix = file_path.suffix.lower()
        use_line_count = rdf_format in LINE_BASED_FORMATS

        if suffix == ".zip":
            with zipfile.ZipFile(file_path, "r") as z:
                inner_name = z.namelist()[0]
                with z.open(inner_name) as f:
                    if use_line_count:
                        return str(file_path), _count_lines_binary(f), None
                    content = f.read().decode("utf-8")
            data = orjson.loads(content)
            return str(file_path), _count_jsonld_triples(data), None
        elif suffix == ".gz":
            if use_line_count:
                with gzip.open(file_path, "rb") as f:
                    return str(file_path), _count_lines_binary(f), None
            with gzip.open(file_path, "rb") as f:
                data = orjson.loads(f.read())
            return str(file_path), _count_jsonld_triples(data), None
        else:
            if use_line_count:
                with open(file_path, "r", encoding="utf-8") as f:
                    return str(file_path), _count_lines_text(f), None
            with open(file_path, "rb") as f:
                data = orjson.loads(f.read())
            return str(file_path), _count_jsonld_triples(data), None
    except Exception as exc:
        return str(file_path), 0, str(exc)


def process_files(
    files: list[Path],
    rdf_format: str,
    max_workers: int | None,
    show_per_file: bool,
    keep_going: bool,
    unit_name: str,
) -> tuple[int, list[tuple[str, str]]]:
    workers = max_workers or multiprocessing.cpu_count()
    if workers < 1:
        workers = 1

    total_count = 0
    results: list[tuple[str, int]] = []
    failures: list[tuple[str, str]] = []
    chunksize = max(1, len(files) // (workers * 4))

    worker_fn = partial(count_in_file, rdf_format=rdf_format)

    with create_progress() as progress:
        task = progress.add_task(f"Counting {unit_name}", total=len(files))

        with Pool(processes=workers) as pool:
            for file_path, count, error in pool.imap_unordered(
                worker_fn, files, chunksize=chunksize
            ):
                if error:
                    failures.append((file_path, error))
                    if not keep_going:
                        progress.console.print(
                            f"[red]Error processing {file_path}: {error}[/red]"
                        )
                        progress.advance(task)
                        pool.terminate()
                        break
                    progress.console.print(
                        f"[yellow]Error processing {file_path}: {error} (continuing)[/yellow]"
                    )
                else:
                    total_count += count
                    if show_per_file:
                        results.append((file_path, count))

                progress.advance(task)

    if show_per_file and results:
        width = max(len(path) for path, _ in results)
        for path, count in sorted(results):
            print(f"{path.ljust(width)} : {count}")

    return total_count, failures


def main() -> None:  # pragma: no cover
    args = parse_args()

    if args.prov_only and args.data_only:
        print("Error: --prov-only and --data-only are mutually exclusive.")
        return

    try:
        files = discover_files(
            args.directory,
            args.pattern,
            args.recursive,
            args.prov_only,
            args.data_only,
        )
    except ValueError as exc:
        print(f"Error: {exc}")
        return

    if not files:
        print("No files found matching the provided pattern.")
        return

    unit_name = "quads" if args.format in QUAD_FORMATS else "triples"

    total, failures = process_files(
        files,
        args.format,
        args.workers,
        args.show_per_file,
        args.keep_going,
        unit_name,
    )

    print(f"Total {unit_name}: {total}")

    if failures:
        print(f"\nFiles with errors ({len(failures)}):")
        for path, error in failures:
            print(f"  {path}: {error}")


if __name__ == "__main__":  # pragma: no cover
    main()
